github.com:
    users:
        56snty:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: 56snty
